# Generated by Django 2.1.2 on 2018-11-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Industry_name', models.CharField(max_length=50)),
                ('Num_visiting', models.IntegerField(default=1)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.CharField(choices=[('1', '9:30'), ('2', '11:30'), ('3', '14:30')], default='9:30', max_length=10)),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checking_slot.Date')),
            ],
        ),
    ]
