# Generated by Django 2.1.2 on 2018-11-08 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking_slot', '0002_auto_20181105_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 8, 22, 50, 54, 5214)),
        ),
    ]
