# Generated by Django 2.1.2 on 2018-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking_slot', '0003_auto_20181108_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='event_date',
            field=models.DateField(default='11/08/2018'),
        ),
    ]
